### ISSUE TITLE
sbt writes too much to almost full disks

### ISSUE THREAD

**Issue by kwalcock** [clulab/clulab#1]
Something like these lines needs to be placed into a configuration file on the servers:
```
-ivy /data1/home/you/ivy2
-Djava.io.tmpdir=/data1/home/you/tmp
```
On my machine it looks like the first needs to be in `sbtopts` and the second in `sbtconfig.txt`.

**Comment by kwalcock** [comment]
On Linux, sbtopts is sufficient.  It is unfortunate that the java.io.tmpdir will not be created automatically if it doesn't already exist and as a result, Java will complain and crash.  One way around that is to modify the sbt script to create the directory, but that script will probably be overwritten each time that sbt is updated and create maintenance problems.  To get around all that, I propose to add `/etc/profile.d/sbt-config.sh` with contents similar to
```bash
if [ -z "$SBT_TMP_DIR" ]; then
    export SBT_TMP_DIR="/data1/home/$USER/sbttmp"
fi

if [ ! -e "$SBT_TMP_DIR" ]; then
    mkdir -p "$SBT_TMP_DIR"
    cp /etc/profile.d/sbt-README.tmp "${SBT_TMP_DIR}/README"
fi

if [ -z "$SBT_IVY_DIR" ]; then
    export SBT_IVY_DIR="/data1/home/$USER/sbtivy"
fi

if [ ! -e "$SBT_IVY_DIR" ]; then
    mkdir -p "$SBT_IVY_DIR"
    cp /etc/profile.d/sbt-README.ivy "${SBT_IVY_DIR}/README"
fi
```
Next, `/etc/sbt/sbtopts` has these lines added:
```bash
# This has been added specifically for the clulab.
-Djava.io.tmpdir=$SBT_TMP_DIR
-ivy $SBT_IVY_DIR
```
The drawback is that people who might not ever use `sbt` see these weird files in their /data1/home directories.  That's partially addressed with the README files:
```
This file and this directory are automatically created when you login
by /etc/profile.d/sbt-config.sh.  sbt produces many temporary files
that normally accumulate in /tmp and cause problems with our servers,
so sbt is configured in /etc/sbt/sbtopts to use this directory instead.
Please remove the directory periodically so that the disk space is
freed up for others to use.  See also the clulab/clulab wiki page at
https://github.com/clulab/clulab/wiki/Lab-Servers for more information.
You can override this behavior by reassigning the environment variable
$SBT_TMP_DIR.
```
That's my suggested solution.  If sbt it unlikely to change much, the contents of sbt-config.sh could be put into that file instead and then it should only affect people who use the sbt command.  I'm not yet sure how either of these work if the version of sbt configured for a project is different from the version installed.  Which configuration file is used then, if any?

**Comment by MihaiSurdeanu** [comment]
This is almost there, with the exception that on our servers /data1 is just a folder under /. So, the problem remains the same: root will fill up because of sbt... How about something simpler, where instead of /data1/home... we use ~/sbttmp for each user? This would be stored on the file server, which is slower, but it has more space. And won't block any / partition.
Your scripts still apply.
We should also something to the instructions to tell users to periodically clean up the ~/sbttmp folder. My hope is that since this is a top folder in their home dir, people won't forget that much about this...

In any case, can you please start a Wiki page with these instructions in our lab's repo at: 
https://github.com/clulab/clulab/wiki
Maybe break it in two sections: one for sysadmins (that is, us), one for all users?

Thanks!

**Comment by kwalcock** [comment]
Sure.  Some of the advice at the top of https://github.com/clulab/clulab/wiki/Lab-Servers conflicts a little and maybe I should edit it to match.
```
log files or intermediate results, under the /data1/
sbt -Djava.io.tmpdir=/data1/home/you/tmp
```
The default location of the ivy directory is ~/.ivy2, but unhiding it probably increases the chances that it will be cleaned.

**Comment by kwalcock** [comment]
Rather than to create these temporary directories even for people who never use sbt, I'm deciding it would be better to modify the sbt startup program to create them on demand.  This involves adding a little code similar to this towards the end of sbt instead of adding code to /etc/profile.d.

```bash
# Special for clulab create temporary directory and add README files.
sawIvy=false
for arg in "$@"
do
#  echo "$arg"
  if [[ $sawIvy == "true" ]]; then
    sawIvy=false
    if [ ! -e "$arg" ]; then
      mkdir -p "$arg"
      cp /etc/sbt/sbt-README.ivy "${arg}/README"
    fi
  else
    case "$arg" in
      -ivy) sawIvy=true ;;
      -Djava.io.tmpdir=*)
        subarg=${arg:17}
        if [ ! -e "$subarg" ]; then
          mkdir -p "$subarg"
          cp /etc/sbt/sbt-README.tmp "${subarg}/README"
        fi
        ;;
    esac
  fi
done
```

**Comment by MihaiSurdeanu** [comment]
I like this. But this means everybody would need to change their sbt startup script, no?

**Comment by kwalcock** [comment]
The script should be the shared one at /usr/bin/sbt unless someone has a customized, local copy.  It would need to be changed on each server, just like the profile program and /etc/sbt/sbtopts where the settings are actually stored.  In /etc/sbt/sbtopts, lines like

```bash
# This has been added specifically for the clulab.
-Djava.io.tmpdir=~/sbttmp
-ivy ~/sbtivy
```
would still be added.  People can override the values with an .sbtopts in their project directory or on the command line.

**Comment by MihaiSurdeanu** [comment]
Cool.


On September 9, 2019 at 12:35:33 PM, Keith Alcock (notifications@github.com)
wrote:

The script should be the shared one at /usr/bin/sbt unless someone has a
customized, local copy. It would need to be changed on each server, just
like the profile program and /etc/sbt/sbtopts where the settings are
actually stored. In /etc/sbt/sbtopts, lines like

# This has been added specifically for the clulab.
-Djava.io.tmpdir=~/sbttmp
-ivy ~/sbtivy

would still be added. People can override the values with an .sbtopts in
their project directory or on the command line.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/clulab/clulab/issues/1?email_source=notifications&email_token=AAI75TTGABABTSN5735FBCDQI2QQJA5CNFSM4IUNKQR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD6IYY4Y#issuecomment-529632371>,
or mute the thread
